- src/App.jsx
- src/pages/Welcome/Form.jsx
- src/pages/Welcome/Top.jsx
- src/pages/Welcome/Welcome.jsx
- src/styles/app.css
- src/styles/reset.css
1. Welcome 페이지 퍼블리싱하였습니다.
2. App.jsx에 welcome 페이지 라우터 추가하였습니다!! 확인해주세요!
> #8 - Feat: welcome 페이지 퍼블리싱

- src/pages/Splash/Splash.jsx
* Splash 화면에서 Welcome 화면으로 특정 시간 후에 넘어가는 기능 구현하였습니다.
* 추후에 구현할 기능
1. 페이지 전환될 때 애니메이션 효과 넣기 (라이브러리 설치 필요함)
2. 로그인 여부에 따라 다른 페이지로 전환시키기
> #15 - Feat: Splash 화면에서 Welcome 화면으로 특정 시간 후에 넘어가는 기능 구현

- src/App.jsx
- src/pages/ChatList/ChatList.jsx
1. 채팅 목록 페이지 퍼블리싱 완료
2. App.jsx에 라우터 추가 완료
두 가지 완료했습니다! 확인 부탁드립니다!
> #11 - Feat: 채팅 목록 페이지 퍼블리싱

- .eslintrc.json
- src/App.jsx
- src/components/Form/Form.jsx
- src/components/Title/Title.jsx
- src/pages/Join/Join.jsx
- src/pages/Login/Login.jsx
- src/pages/Splash/Splash.jsx
- src/styles/app.css
1. 로그인 페이지 퍼블리싱
2. 회원가입 페이지 퍼블리싱
3. App.jsx에 Login, Join 라우터 추가
4. components 폴더에 재사용될 Form, Title 컴포넌트 추가
5. app.css에 머스캣 색상도 변경했습니다!
> #18 - Feat: 로그인 페이지 + 회원가입 페이지 퍼블리싱

- package-lock.json
- package.json
- src/App.jsx
- src/pages/Welcome/Welcome.jsx
- src/pages/Welcome/transition.css
- src/styles/app.css
1. 애니메이션 효과를 넣기 위해서 framer-motion을 설치하였습니다.
2. 애니메이션 효과를 넣기 위해서 App.jsx에서 Splash, Welcome 라우터를 수정하였습니다.
3. app.css에 ```button```에 ```cursor: pointer;``` 효과를 추가하였습니다.
4. 불필요한 주석은 PR merge 되면 develop branch에서 바로 지우도록 할게요!! (제가 개발할 때 알아보려고 쓴 불필요한 주석입니다!! 무시하셔도 됩니다.)
5. transition.css도 삭제를 깜빡하고 못 해서 merge되면 바로 삭제하겠습니다. 쓰이지 않는 css 파일입니다.
> #22 - Feat: Splash 페이지에서 Welcome 페이지로 전환 애니메이션 설정

- src/App.jsx
- src/pages/ChatRoom/ChatRoom.jsx
1. 채팅 페이지 퍼블리싱 완료 (모달은 따로 구현하겠습니다)
2. App.jsx에 ChatRoom 라우터 추가했습니다!
> #20 - Feat: 채팅 페이지 퍼블리싱

- src/components/Form/Form.jsx
- src/pages/Welcome/Welcome.jsx
- src/styles/app.css
1. 로그인 API 연동해서 콘솔 창에 결과 가져오기 기능 구현
2. 아이디, 비밀번호 Input 값 없을 시에 버튼 비활성화 기능 구현
3. 필요없는 주석 삭제
4. 머스캣 진한 색상도 추가하였습니다!
5. 개발하면서 사용한 console.log는 로그인 기능 개발 마무리할 때 삭제하겠습니다!
> #24 - Feat: 로그인 기능 구현 (1)

- .eslintrc.json
- src/components/Form/Form.jsx
1. 사용자가 이메일을 입력할 때 정규표현식을 사용하여 유효성 검사를 진행하여 경고 문구를 띄어주는 기능을 구현하였습니다.
2. 로그인 API를 이용하여 이메일 또는 비밀번호가 일치하지 않는 상태에서 로그인 버튼을 눌렀을 때 경고 문구를 띄어주는 기능을 구현하였습니다.
3. 이스케이프 문자를 사용하기 위해서 ESLint에 규칙을 추가하였습니다.
> #28 - Feat: 로그인 기능 구현 (2)

- src/pages/ChatList/ChatList.jsx
1. Link 연결 라우터 사용해서 변경
2. NewIcon과 프로필 이미지 가상요소로 변경
3. Header 부분 flex 사용해서 재배치
수정했습니다! 잊어버리고 주석 안 지운 부분이 있어서 다음 작업 때 삭제하겠습니다!!
> #25 - Fix: 페이지 Link 연결 방식 변경

- src/pages/ChatRoom/ChatModal.jsx
- src/pages/ChatRoom/ChatRoom.jsx
1. useState 사용해 더보기 아이콘 클릭 시 오픈되는 모달 기능 구현
2. useState와 useEffect 사용해서 input에 값 입력 시 버튼 색상 변경
3. 말풍선 색상 변경
세 가지 완료했습니다!
> #30 - Feat: 채팅 페이지 세부 기능 구현

- src/components/TabMenu/TabMenu.jsx
음...? prettier 적용했는데 prettier 적용한게 커밋이 안되서 제가 올렸던 코드중에서 안쓰는부분 잔재를 겸사겸사 발견해서 함께 올려봤습니다. 그런데도 제 개인적으로 수정한 부분만 커밋되네요....뭐지
> #49 - Refactor: 220707 0시기준 전체 src폴더 prettier 적용 및 TabMenu 코드 살짝 정리

- src/App.jsx
- src/components/Button/Button.jsx
- src/components/Form/Form.jsx
- src/components/ProfileForm/ImageButton.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
- src/pages/ProfileSetting/ProfileSetting.jsx
1. 프로필 수정 페이지 퍼블리싱 완료하였습니다.
2. App.jsx에 라우터 추가하였습니다.
3. 조건에 따라 버튼의 크기, 글자 크기, padding 크기가 다르게 적용되도록 했습니다.
4. 버튼에 있는 margin 삭제하였습니다.
* **한꺼번에 alt랑 ir 검토하겠습니다 ㅠㅠ 또 까먹었네요**
> #51 - Feat: 프로필 수정 페이지 퍼블리싱 + 버튼 컴포넌트 작업

- src/pages/Upload/Upload.jsx
버튼만 추가하고 기능이 빠져서 추가했습니다
버튼 컴포넌트 잘 작동합니다~!
> #59 - Feat: 게시글 작성 페이지 버튼 기능 추가

- src/components/Form/Form.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/pages/Join/Join.jsx
1. 로그인, 회원가입 기능을 분리하였습니다.
2. 이메일 검증 API를 사용하여 회원가입이 되어있는 이메일을 입력하면 경고 문구가 뜨도록 하였습니다.
3. 회원가입 화면에서 비밀번호를 6자리 이하로 설정하면 경고 문구가 뜨도록 하였습니다.
4. 회원가입 화면에서 이메일 유효성 검사를 하여 통과하지 못하면 경고 문구가 뜨도록 하였습니다.
> #54 - Feat: 회원가입 기능 구현 (1)

- src/pages/Join/Join.jsx
수정하였습니다!
혹시나 여유되시면 버그 테스트 한 번씩 부탁드릴게요~~!!
* ### 회원가입 되어있는 아이디
junsang8921@gmail.com
jisang8921!
> #64 - Fix: 회원가입 경고 문구 중복 현상 수정

- src/components/ProfileForm/InputTitle.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/Join/Join.jsx
- src/store/UserInfo.js
- src/store/index.js
1. 프로필 설정, 수정 페이지의 ```margin-bottom``` 수정하였습니다.
2. TopMenuBar.jsx 컴포넌트에서 Link 오류가 있어서 버튼 태그로 수정하였습니다!
> #71 - Fix: 프로필 설정, 수정의 margin 수정

- src/components/ProfileForm/ProfileForm.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/pages/Join/Join.jsx
- src/store/UserInfo.js
1. 리덕스에 id, password 말고도 계정 이름, 계정 ID, 소개를 추가하였습니다.
2. 프로필 Input 글자 색상이 너무 연해서 변경하였습니다.
> #73 - Refactor: Redux에 유저 정보 추가, 프로필 Form 글자 색상 변경

- src/App.jsx
- src/components/FollowList/FollowList.jsx
- src/components/UserCell/UserCell.jsx
- src/pages/Following/Following.jsx
- src/pages/Join/Join.jsx
- src/store/UserInfo.js
1. page/Follower.jsx에서 중복으로 인한 에러 해결하였습니다
2. App.jsx에 라우터 추가하였습니다.
3. Following.jsx 페이지 추가하였습니다
> #78 - Feat: 팔로잉 목록 페이지 퍼블리싱

- src/components/Form/Form.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/styles/app.css
1. input 창에 focus될 때 border-bottom 색상이 바뀌도록 하였습니다.
2. **app.css에 input창이 focus될 때 outline이 생기지 않도록 코드 추가하였습니다!**
* ### 프로필 설정 추가 기능
1. 이름의 길이가 2~10자가 아니면 경고 문구를 띄우도록 하였습니다.
3. 중복된 계정 ID를 입력하고 버튼을 클릭하면 중복 계정 경고 문구를 띄우도록 하였습니다.
4. 계정 ID 유효성 검사 기능을 구현하였습니다.
* ### 프로필 설정 기능 테스트 방법
1. 하고 싶은 ID, PW를 /join 페이지에서 입력하고 다음 버튼을 누릅니다.
2. 이름을 설정하면서 경고 문구가 잘 뜨는지 확인합니다.
3. 계정 ID에 한글 및 지정된 특수문자 이외의 문자들을 입력하면서 경고 문구가 잘 뜨는지 확인합니다.
5. 계정 ID를 ```dbwnstkd3```으로 입력하시고 소개글까지 입력하여 버튼을 누르면 중복 계정에 대한 문구가 잘 뜨는지 확인합니다.
> #77 - Feat: 프로필 설정 기능 추가 구현, input focus시 border 색상 변경

- src/components/Button/Button.jsx
- src/components/ProfileForm/ImageButton.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/Join/Join.jsx
- src/pages/Login/Login.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
- src/pages/ProfileSetting/ProfileSetting.jsx
- src/pages/Splash/Splash.jsx
- src/pages/Welcome/Form.jsx
- src/pages/Welcome/Top.jsx
- src/pages/Welcome/Welcome.jsx
1. div 태그나 DOM fragment 전부 확인하고 Semantic한 태그로 변경하였습니다.
2. 이미지 태그에 전부 alt 추가하였스빈다.
3. section이나 article 태그 사용 시에 ir className 처리해서 설명 텍스트 추가하였습니다.
> #85 - Refactor: Semantic한 태그로 변경 + ir 기법 추가

- src/components/ProfileForm/ProfileForm.jsx
- src/pages/Login/Login.jsx
- src/store/UserInfo.js
1. 로그인 페이지에서 아이디, 비밀번호를 입력하시고 로그인 버튼을 누르시면 Redux에 loginId와 loginToken이 담깁니다.
2. 페이지 전환 시에 데이터 전달은 확인했습니다.
> #88 - Refactor: Redux 데이터에 token 추가 및 API 연동 테스트

- .prettierrc.json
- src/pages/Login/Login.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
- src/store/UserInfo.js
* ## 로그인, 회원가입 API 이외에 거의 모든 API를 사용하실 때 accessToken을 사용하셔야 하기 때문에 꼼꼼히 읽어주시면 감사하겠습니다!!
* ### 사용 방법
1. localStorage.getItem 메서드를 사용해서 accessToken 값을 가져온다.
2. header에 accessToken 값을 템플릿 리터럴로 넣어준다.
3. 반드시 url, data, header 순서대로 서버에 보내셔야 합니다!! 제가 코드 첨부할테니 같은 순서로 사용하시면 됩니다!!
> #95 - Feat: token localStorage 저장 + 프로필 수정 기능 구현

- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/Upload/Upload.jsx
1. 글과 이미지 전송하고 응답받기 성공
2. 닫기 버튼 누를 경우 이미지 삭제 기능 구현 완료
3. TopMenuBar에 uploadButton 버튼 추가
다중 이미지는 계속 실패해서 더 해 봐야 할 것 같고, 토큰은 url 변경하니까 안 넘어오길래 변수에 담아서 테스트 했습니다!
> #79 - Feat: 게시글 업로드 기능 구현

- src/App.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/Search/Search.jsx
ui먼저 퍼블리싱 완료하였고 검색 페이지로서 TopMenuBar에 해당 요소들을 첨가했습니다~! 추후에 리팩토링할때 컴포넌트화 분리되지 않은 부분은 추가적으로 수정하겠습니다. 검색기능 구현은 아직~!
> #107 - Feat: 검색페이지 구현 (ui만)

- src/pages/Upload/Upload.jsx
1. 임시적으로 로컬스토리지에서 프로필 이미지 얻어 오도록 코드 추가
2. 이미지 서버 통신 완료
3. 이미지 개수에 따라 크기 변경되도록 스타일 변경
세 가지 완료했습니다! 계정 검색 input이 모든 페이지에 적용되어 있던데 이 부분 나중에 수정해 주시면 감사하겠습니다~!
> #112 - Feat: 사용자 프로필 가져오기 및 이미지 서버 통신

- src/components/ProfileForm/ImageButton.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/pages/HomeEmpty/HomeEmpty.jsx
- src/pages/Login/Login.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
* 이미지 src가 다음과 같이 보내지도록 설정하였습니다.
> #113 - Test: 프로필 이미지 가져오기 테스트

- .prettierrc.json
- src/App.jsx
1. App.jsx 수정했습니다. (404 에러 해결)
* 이제 Switch 태그 안에 새로운 컴포넌트 넣으셔야 합니다!
2. 프리티어 80 -> 100으로 수정했습니다!
> #121 - Fix: 404 페이지 오류 수정

- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/HomeEmpty/HomeEmpty.jsx
- src/pages/Search/Search.jsx
삼항연산자 표기가 잘못되어 TopMenuBar 컴포넌트를 사용하는 모든 페이지에 Search input이 보이는 문제가 생겼었더라구요. 바로 수정하였습니다ㅎㅎ 그런데 하나 궁금한것이... 원래 falsy값이 기본 메인인가요? 기본 출력값이  true 인줄 알고 ture에다가 온갖 코드 다 써놓다가 혹시몰라서 위치 바꾸니까 잘 실행되네요...
> #124 - Fix: 상단 검색창 기본 표시 변경

- src/components/PostTextBar/PostTextBar.jsx
- src/pages/Post/Post.jsx
- src/pages/Upload/Upload.jsx
- src/store/PostInfo.js
- src/store/index.js
redux에 upload 된 post 정보 넣어서 출력 성공했습니다!
사용자 프로필 이미지는 로컬스토리지만 먹히고 불러오는 게 안 돼서 더 봐야 할 것 같습니다 ㅜㅜ
이미지 슬라이드는 우선 스크롤로만 넣어 뒀습니다~!
> #118 - Feat: Redux에 Upload 정보 추가

- src/components/Button/Button.jsx
- src/components/Button/MoreButton.jsx
- src/components/Form/Form.jsx
- src/components/PostTextBar/PostTextBar.jsx
- src/components/Profile/Profile.jsx
- src/components/ProfileForm/ImageButton.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/ChatRoom/ChatRoom.jsx
- src/pages/Join/Join.jsx
- src/pages/Login/Login.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/pages/NotFound/NotFound.jsx
- src/pages/Post/Post.jsx
- src/pages/Search/Search.jsx
- src/pages/Upload/Upload.jsx
- src/pages/YourProfile/YourProfile.jsx
- src/styles/app.css
1. app.css 에 --color-active: #fff 추가하였습니다.
2. YourProfile.jsx, MyProfile.jsx 페이지의 버튼에 --color-active색 부여하였습니다.
- 채팅 버튼과 공유 버튼 아이콘 이미지 삽입하였습니다.
3. Button.jsx 컴포넌트에 active 버튼을 위한 속성 추가하였습니다.
고민한 시간들이 무색하게 성공은 갑자기 찾아오네요ㅋㅋㅋㅋㅋㅋㅋㅋ
> #101 - Refactor: 사용자 프로필 페이지 버튼 색 변경

- src/components/Button/Button.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
- src/components/UserCell/UserCell.jsx
- src/pages/HomeEmpty/HomeEmpty.jsx
- src/pages/Post/Post.jsx
- src/pages/Search/Search.jsx
- src/pages/YourProfile/YourProfile.jsx
1. UserCell 컴포넌트에  팔로우 <-> 취소 토글 기능 구현했습니다.
2. Profile 컴포넌트에도 팔로우 <-> 언팔로우 토글 기능 구현했습니다.
> #129 - Refactor: 팔로우 여부에 따른 버튼 변화 구현 및 토글 적용

- src/components/PostTextBar/PostTextBar.jsx
- src/pages/Login/Login.jsx
- src/pages/Post/Post.jsx
- src/pages/Upload/Upload.jsx
- src/store/PostInfo.js
- src/store/UserInfo.js
UserInfo 리듀서에 사용자 프로필 이미지 담아서 불러왔습니다!
이미지 슬라이드를 피그마처럼 구현하려고 했는데 생각보다 마음대로 안 돼서 일단 Upload 페이지처럼 다중 이미지일 때 크기 줄여서 보이게 해 뒀습니다! 게시글 수정 기능까지 완료하면 다시 도전해 볼게요!
> #128 - Refactor: UserInfo에 이미지 담기 및 이미지 슬라이드 형식 변경

- src/components/Button/Button.jsx
Login, Join 페이지 등에서 비활성화 버튼이 작동 안해서 수정하였습니다!
> #138 - Fix: 버튼 컴포넌트 수정

- src/components/Button/MoreButton.jsx
- src/components/Modal/Modal.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
모달창 생각보다 너무 어렵네요...ㅜㅜ 조금 더 해보고 헬프쳐보겠습니다.
<진행상황>
1. UI 컴포넌트화 구현 완료
2. 설정 및 개인정보 바로가기 연결 완료, 로그아웃창은 Link만 설정
<해야할 내용>
1. MoreButton과의 연결작업
2. '로그아웃' 클릭 시 부가적인 alert 창 띄우기
2-1.  로그아웃 후 메인 로그인 화면으로 돌아가게하기
4. 추가적인 인터렉션 작업
> #127 - Feat: Modal창 UI 완성 및 개인정보 가기 완료, TopMenu 아이콘 연결중

- src/App.jsx
- src/components/PostView/PostProfile/PostProfile.jsx
- src/components/PostView/PostView.jsx
- src/pages/Login/Login.jsx
- src/pages/PostUpdate/PostUpdate.jsx
- src/store/PostInfo.js
- src/store/UserInfo.js
1. 게시글 수정 기능 구현 완료
2. UserInfo에 `UserAccount`, `UserName` 추가해서 게시글 작성자 프로필에 띄울 수 있게 했습니다! PostInfo에서 받으려니 글 쓸 당시의 프로필이 담겨서 사용자가 프로필 변경했을 때 반영이 안 될 것 같더라고요!
테스트 해보시고 문제 있는 부분 알려주세요~
> #134 - Feat: 게시글 수정 기능 구현

- src/components/PostView/PostProfile/PostProfile.jsx
- src/components/PostView/PostView.jsx
- src/pages/PostUpdate/PostUpdate.jsx
- src/pages/Upload/Upload.jsx
- src/store/PostInfo.js
- src/store/UserInfo.js
UserInfo에서 사용자 정보 담아와서 프로필에 뿌렸더니 로그인된 사용자로 뜬다는 걸 망각하고 실수해서 PostInfo로 다시 되돌려놓았습니다!!!
> #149 - Refactor: 게시글 사용자 프로필 가져오기 수정

- src/App.jsx
- src/components/FollowList/FollowList.jsx
- src/components/UserCell/UserCell.jsx
- src/pages/FollowListPage/FollowListPage.jsx
- src/pages/HomeEmpty/HomeEmpty.jsx
- src/pages/Login/Login.jsx
- src/pages/ToProfile/ToProfile.jsx
- src/store/UserInfo.js
* 내가 팔로우 하지 않은 계정일 때
* 내가 팔로우한 계정일 때
* 팔로우 버튼 토글 추가하였습니다.
> #154 - Feat: 팔로워 목록에서 나를 팔로우하고 있으면 다른 버튼을 렌더링하기

- src/App.jsx
- src/components/PostView/PostProfile/PostProfile.jsx
- src/components/PostView/PostView.jsx
- src/components/TabMenu/TabMenu.jsx
- src/pages/UserProfile/UserProfile.jsx
- src/store/PostInfo.js
- 게시글 작성 전
- 게시글 작성 후 
- 다른 아이디로 로그인해서 다시 확인
- 왜인지는 모르겠지만 이미지가 여러장이면 오류가 뜹니다..! 추후 수정하겠습니다.
올리고 보니 날짜가 없군요^^?
> #153 - Feat: 프로필 페이지에 게시글 띄우기 구현

- src/components/Button/MoreButton.jsx
- src/components/Modal/LogoutModal.jsx
- src/components/Modal/Modal.jsx
> #158 - Refactor: 모달창 로그아웃 추가모달 띄우기 실행중...help

- src/components/Modal/Modal.jsx
> #164 - Refactor: 게시글 수정 버튼 오류 수정

- src/components/Modal/Modal.jsx
- src/components/TopMenuBar/TopMenuBar.jsx
게시글 수정 페이지 연결하고 뒤로 가기 클릭 시 이동 경로 프로필 페이지로 바꿨습니다!
> #165 - Refactor: 게시글 수정 페이지 연결

- src/pages/UserProfile/UserProfile.jsx
프로필페이지에서 프로필 수정 버튼 눌렀을 때 수정하는 페이지로 넘어가게 수정했습니다!!!!!
> #173 - Fix: 프로필 수정 버튼 url 오류 수정

- src/App.jsx
- src/components/PostView/PostView.jsx
- src/components/ProductFrom/ImageButton.jsx
- src/components/ProductFrom/ProductFinal.jsx
- src/components/ProductFrom/ProductForm.jsx
- src/components/ProductFrom/UploadItemImg.jsx
- src/components/ProductFrom/UserInfoInput.jsx
- src/components/SaleProduct/SaleProduct.jsx
- src/components/SaleProductItem/SaleProductItem.jsx
- src/components/TabMenu/TabMenu.jsx
- src/pages/AddProduct/AddProduct.jsx
- src/pages/UserProfile/UserProfile.jsx
- src/store/PostInfo.js
- src/store/ProductInfo.js
- src/store/index.js
> #157 - Feat: 프로필 페이지에서 상품 등록 기능 구현

- src/components/Button/MoreButton.jsx
- src/components/Modal/Modal.jsx
- src/components/PostView/PostProfile/PostProfile.jsx
- src/components/PostView/PostView.jsx
- src/pages/PostUpdate/PostUpdate.jsx
> #179 - Fix: 게시글 수정 시 postId에 맞는 기존 데이터 가져오기

- src/components/Modal/LogoutModal.jsx
- src/components/Modal/Modal.jsx
- src/components/PostView/PostProfile/PostProfile.jsx
- src/components/PostView/PostView.jsx
- src/store/PostInfo.js
PostProfile을 내 프로필 페이지 들어가면 로그인 정보로 받아오려고 변경하신 것 같더라고요?!
다른 사용자의 게시글 삭제 했을 때 오류 뜨는 것 확인하려고 들어갔다가 다른 사용자 프로필도 지금 로그인한 정보로 떠서 props로 받아서 넘겼습니다!
삭제 기능, 예외 경우에 경고 알림, 위에서 설명한 부분까지 잘 동작하는 것 확인했습니다~!
> #181 - Feat: 게시글 삭제 기능 구현

- src/App.jsx
- src/components/PostView/PostView.jsx
- src/components/TabMenu/TabMenu.jsx
- src/pages/Home/Home.jsx
피드페이지 제작중에 오류가 생겨 먼저 머지 요청드려봅니다. map과 key 연동이 안되네요....
> #102 - Feat: 메인 피드페이지 제작

- src/components/Modal/LogoutModal.jsx
오류 고쳤고 게시글 삭제 성공하면 새로고침 되게 했습니다!
> #190 - Fix: 게시글 삭제 성공 시 알림 안 뜨는 오류 수정

- src/components/PostCard/PostCard.jsx
- src/components/PostView/PostView.jsx
- src/components/TabMenu/TabMenu.jsx
- src/pages/UserProfile/UserProfile.jsx
1. PostView로 가지고 오던 프로필 피드를 서로 가지고 오는 함수가 달라 PostCard로 분리
2. TabMenu에서 클릭 시에 바뀐 데이터 들고 오던 방식도 페이지 렌더링 시에 가지고 올 수 있도록 변경
> #193 - Refactor: 프로필 페이지 데이터 가져오는 방식 변경 및 페이지 분리

- src/App.jsx
- src/components/PostCard/PostCard.jsx
- src/components/PostView/PostComment/PostComment.jsx
- src/components/PostView/PostView.jsx
- src/components/SaleProductItem/SaleProductItem.jsx
- src/pages/PostUpdate/PostUpdate.jsx
- src/pages/UserProfile/UserProfile.jsx
- src/store/PostInfo.js
1. postId 따라서 상세 페이지 잘 이동되게 수정
2. /profile 에서 누락된 moreButton 추가
3. /profile 다중 이미지 띄우기 완료
> #195 - Fix: 게시글 상세 페이지 이동 오류 수정

- src/pages/Home/Home.jsx
useHistory 관련 오류코드가 있어 바로 삭제하였습니다.
> #205 - HOTFIX: feature-189 브랜치 오류코드 삭제

- src/components/PostView/PostComment/PostComment.jsx
- src/store/PostInfo.js
1. 게시글 댓글 불러오기 기능 구현 완료
2. 게시글 댓글 작성 시간 계산 후 표시 기능 구현 완료
> #216 - Feat: 게시글 댓글 불러오기 기능 구현

- src/components/PostCard/PostCard.jsx
- src/pages/UserProfile/UserProfile.jsx
> #HOTFIX: 프로필 페이지 배포 오류 테스트 (1)

- src/components/TopMenuBar/TopMenuBar.jsx
- src/pages/Home/Home.jsx
홈 피드에서 말풍선 아이콘 클릭하면 해당 게시글로 이동하게 변경했습니다!
> #222 - Refactor: 피드에서 사용자 게시글로 이동 기능 추가

- src/components/Modal/Modal.jsx
- src/components/ProfileForm/ImageButton.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/components/ProfileForm/UserInfoInput.jsx
- src/pages/Join/Join.jsx
- src/pages/Login/Login.jsx
- src/pages/UserProfile/UserProfile.jsx
- src/store/UserInfo.js
> #225 - Fix: 배포 오류 수정 진행 중

- src/components/Button/MoreButton.jsx
- src/components/Modal/Modal.jsx
- src/components/PostView/PostComment/PostComment.jsx
코드가 지저분한 것 같습니다!!! 다른 좋은 의견 있으시면 마구마구 알려 주세요!!!!
> #230 - Fix: Modal 오류 수정

- src/components/Button/MoreButton.jsx
- src/components/Modal/Modal.jsx
- src/components/PostView/PostProfile/PostProfile.jsx
- src/pages/Home/Home.jsx
- src/pages/PostUpdate/PostUpdate.jsx
#236 - 모달 종류별로 잘 동작하는 것 확인은 했습니다...!
#239  - 글만 작성된 페이지를 이미지를 올려 수정하려고 하니 기존의 비어 있는 이미지 값이 배열로 들어가 출력돼서 없앴습니다!!
> #236 - Fix: Modal 오류 수정

- src/components/PostView/PostComment/PostComment.jsx
최신순으로 정렬되어 있던 댓글을 등록순으로 정렬 순서 변경했습니다
> #241 - Refactor: 댓글 정렬 순서 변경

- src/App.jsx
- src/components/ProfileForm/ProfileForm.jsx
- src/pages/Login/Login.jsx
- src/pages/ModifyProfile/ModifyProfile.jsx
- src/pages/Splash/Splash.jsx
1. 프로필 수정에서 버튼 활성화 안 되는 문제 해결
2. Splash 페이지에서 토큰 보유 여부에 따라서 Welcome 페이지, 피드 페이지로 이동 설정
3. App.jsx에서 토큰 검증해서 유효하면 페이지 렌더링하도록 구현
> #238 - Fix: 프로필 수정 버튼 + Splash 페이지 이동 수정

- src/components/Loading/test.jsx
- src/pages/Home/Home.jsx
- src/pages/YourProfile/YourProfile.jsx
> #281 - Refactor: 피드페이지 validate 오류코드 수정
